server:
  port: 9090

spring:
  config:
    activate:
      on-profile: local

  h2:
    console:
      enabled: true
      path: h2-console

  jpa:
    database: h2
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none

  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:reservation-api;MODE=MYSQL;DB_CLOSE_DELAY=-1"
    username: sa
    password: